peltool: patch work
ibm-openbmc/openpower-pel-parsers pull request #49
Opened 2024-06-05 06:32 UTC by harsh-agarwal1

Fixing eid of -l option from pLID to lEID
This commit changes older --no-plugins to --skip-parser-plugins.
This commit changes older -x/--delete to -c/--clean.
This commit changes --del to --delete

Signed-off-by: Harsh Agarwal <Harsh.Agarwal@ibm.com>

2024-06-05 08:10 UTC, RameshIyyar requested changes

2024-06-05 08:10 UTC, RameshIyyar commented on modules/pel/peltool/peltool.py
> +    eid = ph.lEID
Please avoid mixing multiple changes in a single commit.

Each changes should be pushed separately, with a commit message header that clearly states what you are trying to achieve in a simple sentence. The commit message body should explain why you are making these changes and optionally, how you are implementing them.

In the current commit messages, it's unclear why the changes are being made. For instance, "option names renamed" doesn't provide enough context.

2024-06-05 13:53 UTC, spinler commented
The change looks good, though could you update the commit message to say what you changed in the headline?

2024-06-06 05:02 UTC, RameshIyyar approved these changes

2024-06-06 14:28 UTC, spinler approved these changes

2024-06-06 14:29 UTC, merged